### ISSUE TITLE
[Feature req.] Sharex

### ISSUE THREAD

**Issue by R0GGER** [rubikscraft/Picsur#1]
First of all... Great app! Thanks!
Feature request: Sharex integration as (custom) destination.

**Comment by DuckyBlender** [comment]
bump, was just about to open a request about this too

**Comment by rubikscraft** [comment]
ShareX custom target config generation has been added to code. It will be available in the next release.

**Comment by rubikscraft** [comment]
The new release is here, once you update you should be able to export a ShareX config from the settings.

**Comment by Dyras** [comment]
@rubikscraft Sorry, where do I find this exactly? I can't find a settings menu over at https://picsur.org/ at all. Nor can I find any file for this. Hmm.

**Comment by BartekWolv** [comment]
Any advise how to setup it in Sharex Config?

**Comment by jrycp23nkt** [comment]
> Any advise how to setup it in Sharex Config?

Yes please ! Any advise how to setup it in Sharex Config???

**Comment by deuts** [comment]
> > Any advise how to setup it in Sharex Config?
> 
> Yes please ! Any advise how to setup it in Sharex Config???

I created a guide [here](https://deuts.org/p/picsur-sharex-setup/).
