### ISSUE TITLE
[Feature Request] Allow to disable authentication

### ISSUE THREAD

**Issue by MisterrrX** [rubikscraft/Picsur#104]
It would be great if there was an option to disable authentication entirely.

This allows running the server behind a reverse proxy with forward auth without always having to enter additional credentials. Since the web interface can't be reached without authenticating externally, there is no point in requiring internal authentication.

Thanks in advance, awesome application!

**Comment by CaramelFur** [comment]
You can already do that, if you give the guest user all permissions available, you can do everything without logging in.

**Comment by MisterrrX** [comment]
Ah, I overlooked that, never mind then, thank you!
