### ISSUE TITLE
Upload using API Key?

### ISSUE THREAD

**Issue by tirthpatell** [rubikscraft/Picsur#105]
Hi, didn't find direct answer looking for it so asking here.

I self-hosted it, routed via Cloudflare and it's working good. Now I want to programmatically call the API to upload images from one of my projects [fia-f1-docs-bot](https://github.com/tirthpatell/fia-f1-docs-bot) but is that not possible using just API key? I have to login with username/password?

**Comment by tirthpatell** [comment]
Never mind, only have to login once to get token. Correct understanding right?

**Comment by CaramelFur** [comment]
You can just create an api key in the settings and use that.

**Comment by tirthpatell** [comment]
Hey sorry to follow up on this closed issue, but how to use API key for auth? I had already created it, but I did not see anything in Postman collection related to using API key as auth.

**Comment by CaramelFur** [comment]
Ah no worries, I indeed have not put this anywhere, I'll be sure and add some docs to the settings page with the next release. For now though, if you have the api key `testapikey`, you need to set the `Authorization` header to `Api-Key testapikey` in your request. Hope this helps.

**Comment by tirthpatell** [comment]
Ah so I tried `X-API_KEY` as key, so maybe that's why it didn't work. Anyhow, I tested from Postman and interesting behavior. GET serverInfo works but POST uplaodImage did not work. That gets 403

![CleanShot 2024-12-05 at 10 54 57@2x](https://github.com/user-attachments/assets/7ff9fd36-c723-4968-895d-176125209fe1)

![CleanShot 2024-12-05 at 10 55 54@2x](https://github.com/user-attachments/assets/f975b8ad-94c0-4d87-a708-5e0a45b4de37)

**Comment by tirthpatell** [comment]
Follow-up: The logs show a "Permission Denied" error when uploading an image via the API key. Isn't that unusual? Wouldn't an API key created by an admin have all the necessary permissions?

![CleanShot 2024-12-05 at 20 40 18@2x](https://github.com/user-attachments/assets/b7473a61-b06f-43d8-8b58-59c92e16f499)

**Comment by AndySkaura** [comment]
@tirthpatell 
Do it like this.

![Image](https://github.com/user-attachments/assets/26227b9e-ccd2-4aeb-bb3b-9fefd15e14d3)

**Comment by tirthpatell** [comment]
@AndySkaura Yes, I was able to figure it out, thank you though!
