### ISSUE TITLE
Cached Image expiry time

### ISSUE THREAD

**Issue by karmarcharger** [rubikscraft/Picsur#14]
![image](https://user-images.githubusercontent.com/10364143/190206334-99685e79-ebff-40d2-a72a-e0d7b77af542.png)
Does this setting means that the images uploaded will vanish eventually? what are the variables that can be used in this? how to make the image uploaded not vanish at all?

**Comment by rubikscraft** [comment]
This setting only governs the expiry time of transcoded images.
For example when you request a webp variant of an image, it will convert this image to webp and cache the result. This settings makes it such that this cached result will be deleted after 7 days.
Making this shorter saves on disk space, but will cost more processing power. And making it longer will do the inverse.

Valid values are `Years, Year, Yrs, Yr, Y, Weeks, Week, W, Days, Day, D, Hours, Hour, Hrs, Hr, H, Minutes, Minute, Mins, Min, M, Seconds, Second, Secs, Sec, s, Milliseconds, Millisecond, Msecs, Msec, Ms`. But the default value of 7 days is sufficient for most purposes.

On a sidenote: It is possible to make images expire after a certain time period, but this setting is configured for each invidual image from the image view screen. By default images never expire.
