### ISSUE TITLE
[feature request] Interface customization

### ISSUE THREAD

**Issue by EVOTk** [rubikscraft/Picsur#20]
Hello,
Will it be possible to have options to customize the page title and the top logo, but also the favicon?
![image](https://user-images.githubusercontent.com/45015615/193430134-ac97dc50-6567-4a06-a04e-e03d7213e8b6.png)

Thanks

**Comment by rubikscraft** [comment]
Sorry, the official builds will not support white labeling. You could always still make your own builds with custom branding if it really is required.

**Comment by EVOTk** [comment]
thank you for your reply. 
No, it will stay like that, there is nothing "necessary", but being able to include a personalized title / favicon makes it easier to recognize different instances of Picsur in a browser.

**Comment by rubikscraft** [comment]
Hmm, yeah I can see that being annoying. Maybe I'll add some other way to fix that.

Also, might I ask why you need two instances in the first place? just curious.

**Comment by EVOTk** [comment]
I don't have two instances, but I have a friend I told about Picsur who also has an instance now.
But as said, there is nothing really "necessary". I don't have a big use of Picsur yet, but if I decide to switch completely to Picsur, then this will be a bit annoying, and maybe even more when Picsur has the success it deserves :D
