### ISSUE TITLE
Publish a multiarch docker image

### ISSUE THREAD

**Issue by CalinLeafshade** [rubikscraft/Picsur#3]
The current docker image seems to be x86 only and won't run on a raspberry pi.

Please publish an arm64 version or a multiarch container.

Thanks

**Comment by rubikscraft** [comment]
Hi, a multiarch container wont be possible, since this project contains node modules with native code.
But I can look into adding a native ARM64 container image in the future. I'll add it to the todo list.

**Comment by rubikscraft** [comment]
Support for multiarch arm64 has been added, and will be included in the next major release

**Comment by rubikscraft** [comment]
The next realease is here, you should now be able to run the latest version on your ARM64 device.
